# Generated by Django 2.0.4 on 2019-05-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('besked', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=41)),
                ('description', models.CharField(max_length=41)),
                ('about', models.TextField(max_length=400)),
                ('url', models.URLField(blank=True, null=True)),
                ('sourcecode', models.URLField(blank=True, null=True)),
                ('backend', models.CharField(max_length=150)),
                ('frontend', models.CharField(max_length=150)),
                ('responsive', models.BooleanField()),
                ('highlight', models.BooleanField()),
                ('thumbnail', models.ImageField(upload_to='screenshots/')),
                ('image1_description', models.CharField(max_length=40)),
                ('image1', models.ImageField(upload_to='screenshots/')),
                ('image2_description', models.CharField(max_length=40)),
                ('image2', models.ImageField(upload_to='screenshots/')),
                ('image3_description', models.CharField(blank=True, max_length=40)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('image4_description', models.CharField(blank=True, max_length=40)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
            ],
        ),
    ]
